name: Update Market Data

permissions:
  contents: write

on:
  schedule:
    - cron: '15 10 * * *'
    - cron: '05 22 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    strategy:
      # Hier definieer je je assets!
      matrix:
        asset: [OIL_CRUDE, NATURALGAS, GOLD] 
      # Als 1 faalt, moeten de anderen wel doorgaan
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas

      # Stap 1: Data ophalen (met argument)
      - name: Fetch Data for ${{ matrix.asset }}
        run: python fetch_data.py --epic ${{ matrix.asset }}
        env:
          IDENTIFIER: ${{ secrets.IDENTIFIER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          X_CAP_API_KEY: ${{ secrets.X_CAP_API_KEY }}

      # Stap 2: Data mergen (met argument)
      - name: Merge Data for ${{ matrix.asset }}
        run: python merge_data.py --epic ${{ matrix.asset }}

      # Stap 3: Commit & Push (alleen als er iets gewijzigd is)
      - name: Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add -A
          # Alleen committen als er daadwerkelijk iets te committen valt
          git diff-index --quiet HEAD || git commit -m "Update data for ${{ matrix.asset }}"
          git push
